#!/bin/sh /etc/rc.common
# OpenWRT init script for voice-server

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command sh -c "cd /usr/share/voice-server && /usr/share/voice-server/voiceserver"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall voiceserver
}
